### ISSUE TITLE
"Continue playing" prompt annoyance

### ISSUE THREAD

**Issue by lucisandor** [mozilla/video-bg-play#12]
Now that, thanks to your effort, we can play longer Youtube videos, I am getting the dreaded "Video paused. Continue watching?" prompt. Obviously, I can't reproduce it at will.

On Chromium for Linux, I am using Youtube Nonstop, an extension with the ID `nlkaejimjacpillmajjnopmpbkbnocid` . Looking at its source code, it appears that it employs a webworker,with, every two seconds, checks on `($('.html5-video-player').hasClass("paused-mode"))`. When that turns true, it simulates a `$("video").click();`. Unfortunately, I don't understand how is the Chromium addon distinguishing between manual pauses and server-imposed pauses.

**Comment by buttercookie42** [comment]
Was that with mobile or desktop Youtube? With the former, last month the prompt came reliably after 30 minutes.
Instead of trying to catch the pause after the fact, I am simply regularly updating the time of the last user activity, and at least yesterday, as far as I can tell this was still working with the mobile page.

(A possible difference between desktop and mobile apart, you can of course also never be sure that they're not slowly rolling out some experiment or update that breaks my code again).

**Comment by lucisandor** [comment]
My report refers to this addon as used with Firefox on Android.

**Comment by buttercookie42** [comment]
Can you remember how long it took that prompt to appear?

**Comment by osopolar** [comment]
It seems to happen about 20 to 30 minutes without activities.

**Comment by buttercookie42** [comment]
Tried playing an almost hour-long playlist on Android in the background and didn't experience any problems.

**Comment by osopolar** [comment]
I remember using u block origin. Maybe that blocks something that helps to keep the video playing. It's not related to bg playing, also happens if firefox is in the foreground and I don't touch the phone for that time.

@buttercookie42 did you play the hour-long playlist without touching your mobile? Maybe it only appears if there is no interaction at all. … most people touches their phone so much that they won't notice. I found on businessinsider that "[the typical cellphone user touches his or her phone 2,617 time[s] every day](https://www.businessinsider.com/dscout-research-people-touch-cell-phones-2617-times-a-day-2016-7)"

**Comment by buttercookie42** [comment]
> I remember using u block origin

Of course it also depends on the precise settings, but I tested with uBlock as well.

> did you play the hour-long playlist without touching your mobile?

Yes I did, and besides, for the "Continue playing" prompt it's only interactions with the Youtube page that count.
