### ISSUE TITLE
Video gets stuck!!

### ISSUE THREAD

**Issue by ghost** [mozilla/video-bg-play#2]
After video begins playing, I turn of the screen. After a few minutes you hear no sound, check
your video by turning your screen back on and the video shows the spinning circle like it is 
buffering data from the internet. Not sure if this is just on long videos, I listen to alot of 3 hour
videos on youtube. Please see this link to test it and any of there daily 3 hour videos.
https://www.youtube.com/watch?v=8wXtAH-kK6w

Thank you!!!!

**Comment by misterti** [comment]
Same here. Video plays, but stops buffering until you focus the tab/window again, so it eventualy stops playing. FF 56 android, desktop mode.

**Comment by davidebaldini** [comment]
Same. Maybe this is android stopping background processes to conserve memory? At least I notice this behavior when memory is low. Any suggestions?

**Comment by Maxxee** [comment]
The devices/firmwares are at fault here. Some stupid kind of power management. Maybe there are power options to change this for specific apps.

**Comment by buttercookie42** [comment]
Tested this using the current Firefox Nightly with both playlists and very long videos and everything is working fine. I did come across Youtube's user activity tracking if you don't touch the tab for something like half an hour or so (interrupting playback and asking "Are you still watching?" or some words to that effect), but that should be fixed in version 1.4. Therefore there's nothing more I can do from inside the extension.

I wouldn't absolutely exclude some Firefox bug, but as Maxxee said, this is most likely some overzealous power optimisation feature.
