### ISSUE TITLE
Incompatible with the new Firefox 79.0.5

### ISSUE THREAD

**Issue by niblossi** [mozilla/video-bg-play#25]
It isn't compatible with the new Firefox. It says "not yet available".

**Comment by PtrckDns** [comment]
https://github.com/mozilla/video-bg-play/issues/21#issuecomment-678486384

**Comment by louisabraham** [comment]
Hi, i'm needing this feature as well and can code. How can I help?

**Comment by Malspherus** [comment]
Any updates on this? Will the project be patched for the newest version of Firefox mobile or does it have to be abandoned due to incompatibility?

**Comment by MicroBeast** [comment]
Guys, if you didn't follow Firefox Nightly (at least the news). This addon just land in current Nightly test table.

**Comment by buttercookie42** [comment]
> Any updates on this? Will the project be patched for the newest version of Firefox mobile or does it have to be abandoned due to incompatibility?

See MicroBeast's comment immediately above, but just for completeness – the add-on itself was perfectly compatible all the time (being a simple page script after all, it doesn't even use any add-on APIs which might yet be missing in the new Firefox), the only reason it couldn't be installed is because Mozilla currently insists on only allowing selected add-ons for installation, without there being any clear statement when (or indeed *if*!) this might change…

And of course the problem of Firefox itself interrupting background playback remains for now, and there's nothing the add-on can do about *that*, either.

**Comment by louisabraham** [comment]
Why are we talking about Mozilla as a third party? Isn't this project owned by Mozilla after all?

**Comment by buttercookie42** [comment]
The add-on was originally written by a Mozilla employee, which is probably why it's hosted as part of their Github org, but it was never promoted as an official Mozilla add-on on AMO, and I as the one currently maintaining it am not an employee, either.

(Also I suppose this can be closed now that this seems to have been resolved)
