### ISSUE TITLE
Youtube reloads when I receive a call

### ISSUE THREAD

**Issue by vin-blip** [mozilla/video-bg-play#34]
This addon works perfectly for my Android Firefox browser. Except when I receive a call when a youtube video is playing in the background, the video page gets reloaded as soon as I hang up the call and i lose my watch progress.

**Comment by buttercookie42** [comment]
That's sounds more like an issue with either Firefox and/or Android. (I assume the video/audio still gets stopped when you receive the call, right?)

**Comment by vin-blip** [comment]
Yes, video/audio get stopped when i receive calls.

**Comment by buttercookie42** [comment]
If the video gets stopped by Firefox due to something else (i.e. in this case an incoming call) requesting audio focus, that's outside of the control of what the add-on does. And the fact that the page subsequently gets reloaded is probably some variation of https://bugzilla.mozilla.org/show_bug.cgi?id=1807364, which again is a Firefox and/or Android issue, and nothing the add-on can do anything about.

**Comment by vin-blip** [comment]
Cheers, that actually makes sense to know that it's a firefox bug for sure. Let's hope they fix it someday. :)
