### ISSUE TITLE
video in background doesnt work anymore with Youtube and have some bugs

### ISSUE THREAD

**Issue by OmgNeedAName** [mozilla/video-bg-play#35]
It always worked in the past with any Video from any Website to play it in the background but since a few days its doenst work anymore. Can you please make it work again.

Ty

**Comment by claudiu64** [comment]
Bugs that need to be fixed: 
1. https://bugzilla.mozilla.org/show_bug.cgi?id=1827371 
2. https://bugzilla.mozilla.org/show_bug.cgi?id=1827583

**Comment by distancerunner** [comment]
yes, since the weekend there where some updates on YouTube, where they changed some stuff.
Every 6.5 to 7 minutes the video keeps stuck, if the screen is off. It stuck in loading. If I switch the screen back on, it loads the content and continue playing.

**Comment by NevouAtari1998** [comment]
> It always worked in the past with any Video from any Website to play it in the background but since a few days its doenst work anymore. Can you please make it work again.
> 
> Ty

I've been having the same issue, and it just started happening like three days ago.

**Comment by Jimmyyyy101** [comment]
> It always worked in the past with any Video from any Website to play it in the background but since a few days its doenst work anymore. Can you please make it work again.
> 
> Ty

I'm having the same issue. Youtube will play for a few minutes and then stop. It resumes when I re open the browser. When locking my phone I no longer get the notification bar with play/pause and next on it. If I have been using Spotify then both YouTube and Spotify play at the same time now Instead of cancelling each other out. One thing I have found is if I select "unrestricted" in Firefox battery usage settings it seems to solve the issue of the music stopping but still isn't working as it was before.

**Comment by MittensMcGillicutty** [comment]
> I'm having the same issue. Youtube will play for a few minutes and then stop. It resumes when I re open the browser. When locking my phone I no longer get the notification bar with play/pause and next on it. If I have been using Spotify then both Youtube and Spotify play at the same time now Instead of cancelling each other out. One thing I have found is if I select "unrestricted" in Firefox battery usage settings it seems to solve the issue of the music stopping but still isn't working as it was before.

I am also having this same issue exactly.

**Comment by DarKowGit** [comment]
Just piling on as I noticed the behavior during a bike ride today. On YouTube when screen is off there's no media controls and playback dies, not immediately but soon. Sad panda.

**Comment by buttercookie42** [comment]
Missing media controls looks like a Firefox issue (maybe [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1796359), or something similar?), and beyond that I'm afraid I still can't reproduce anything – I just played back a half-hour long video in background without problems in a current Nightly, even with the screen off.

**Comment by DarKowGit** [comment]
A few more observations. Embedded YouTube player on third-party site behaves correctly--see media controls and video doesn't pause. The problem is on YouTube site proper. Forcing desktop site doesn't help. No difference with 4g or WiFi. I'm running Firefox 111.1.1, Android 12, on Samsung Galaxy S10.

**Comment by buttercookie42** [comment]
Missing media notification is a Firefox issue and nothing to do with this add-on.

**Comment by buttercookie42** [comment]
Seems to be tracked by [this Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1827583), so please follow that for further details.
